# Treasures are determined based on cardinal direction
# Each tile is allowed to have up to 4 non-overlapping oasis entries
# Which are in a list called "oasis"
# A single oasis is described by a u8 of bit flags as follows:
# 0b0001 = NORTH
# 0b0010 = EAST
# 0b0100 = SOUTH
# 0b1000 = WEST

# Read the directions like you would read a map

# Configuration for the cross center
[cross.c]
is_desert = false

# 4 lists describing each part of the starting cross
# Numbered going outwards from the center
# N1
[[cross.n]]
is_desert = false
oasis = ["W"]
# N2
[[cross.n]]
is_desert = false
oasis = ["E"]
# N3
[[cross.n]]
is_desert = false
oasis = ["W"]
# N4
[[cross.n]]
is_desert = false
oasis = ["E"]
# N5
[[cross.n]]
is_desert = false

# E1
[[cross.e]]
is_desert = false
# E2
[[cross.e]]
is_desert = false
oasis = ["S"]
# E3
[[cross.e]]
is_desert = false
oasis = ["N"]
# E4
[[cross.e]]
oasis = ["S"]
is_desert = false
# E5
[[cross.e]]
is_desert = false

# S1
[[cross.s]]
is_desert = false
# S2
[[cross.s]]
is_desert = false
# S3
[[cross.s]]
is_desert = false
oasis = ["E", "W"]
# S4
[[cross.s]]
is_desert = false
# S5
[[cross.s]]
is_desert = false

# W1
[[cross.w]]
is_desert = false
# W2
[[cross.w]]
is_desert = false
oasis = ["N", "S"]
# W3
[[cross.w]]
is_desert = false
# W4
[[cross.w]]
is_desert = false
oasis = ["N", "S"]
# W5
[[cross.w]]
is_desert = false

# Lists describing each of the "decks" used in the game

# Deck 1 
[[decks]]
# 1
[[decks.deck]]
is_desert = true
oasis = ["E | S"]
treasure_n = "none"
treasure_e = "goods:salt"
treasure_s = "rumors"
treasure_w = "none"

# 2
[[decks.deck]]
is_desert = false
oasis = ["N", "S | E"]
treasure_n = "none"
treasure_e = "goods:salt"
treasure_s = "double_water"
treasure_w = "none"

# 3
[[decks.deck]]
is_desert = true
oasis = ["S"]
treasure_n = "none"
treasure_e = "none"
treasure_s = "water"
treasure_w = "none"

# 4
[[decks.deck]]
is_desert = false
oasis = ["N", "S"]
treasure_n = "none"
treasure_e = "none"
treasure_s = "water"
treasure_w = "none"

# 5
[[decks.deck]]
is_desert = false
oasis = ["N | W", "S | E"]
treasure_n = "camels"
treasure_e = "none"
treasure_s = "double_water"
treasure_w = "none"

# 6
[[decks.deck]]
is_desert = false
oasis = ["N | W", "S | E"]
treasure_n = "incense"
treasure_e = "none"
treasure_s = "camels"
treasure_w = "none"

# 7
[[decks.deck]]
is_desert = false
oasis = ["W | N"]
treasure_n = "water"
treasure_e = "none"
treasure_s = "none"
treasure_w = "myrrh"

# 8
[[decks.deck]]
is_desert = false
oasis = ["W", "E"]
treasure_n = "none"
treasure_e = "rumors"
treasure_s = "none"
treasure_w = "goods:gems"

# 9
[[decks.deck]]
is_desert = false
oasis = ["N"]
treasure_n = "water"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 10
[[decks.deck]]
is_desert = false
oasis = ["N", "E | S"]
treasure_n = "none"
treasure_e = "none"
treasure_s = "double_water"
treasure_w = "none"

# 11
[[decks.deck]]
is_desert = true
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 12
[[decks.deck]]
is_desert = true
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 13
[[decks.deck]]
is_desert = false
oasis = ["W | N"]
treasure_n = "rumors"
treasure_e = "none"
treasure_s = "none"
treasure_w = "myrrh"

# 14
[[decks.deck]]
is_desert = true
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 15
[[decks.deck]]
is_desert = false
oasis = ["N"]
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 16
[[decks.deck]]
is_desert = false
oasis = ["S | E"]
treasure_n = "water"
treasure_e = "incense"
treasure_s = "none"
treasure_w = "none"

# 17
[[decks.deck]]
is_desert = false
oasis = ["N | S"]
treasure_n = "none"
treasure_e = "none"
treasure_s = "goods:gems"
treasure_w = "none"


# Deck 2 
[[decks]]
# 1
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 2
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 3
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 4
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 5
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 6
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 7
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 8
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 9
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 10
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 11
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 12
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 13
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 14
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 15
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 16
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 17
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"


# Deck 3
[[decks]]
# 1
[[decks.deck]]
is_desert = true
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 2
[[decks.deck]]
is_desert = false
oasis = ["E"]
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 3
[[decks.deck]]
is_desert = false
oasis = ["S"]
treasure_n = "none"
treasure_e = "none"
treasure_s = "rumors"
treasure_w = "none"

# 4
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 5
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 6
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 7
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 8
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 9
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 10
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 11
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 12
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 13
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 14
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 15
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 16
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 17
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"


# Deck 4
[[decks]]
# 1
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 2
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 3
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 4
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 5
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 6
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 7
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 8
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 9
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 10
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 11
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 12
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 13
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 14
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 15
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 16
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 17
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"


# Deck 5
[[decks]]
# 1
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 2
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 3
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 4
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 5
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 6
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 7
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 8
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 9
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 10
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 11
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 12
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 13
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 14
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 15
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 16
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"

# 17
[[decks.deck]]
is_desert = false
oasis = []
treasure_n = "none"
treasure_e = "none"
treasure_s = "none"
treasure_w = "none"
